<?php

$todoData = [
    "Attend a wedding fair for inspo!",
    "Set your budget",
    "Take out wedding insurance",
    "Hire your wedding planner (if you want one!)",
    "Decide wedding type & theme",
    "Find your venue & catering",
    "Create your guest list & send save the date cards",
    "Book your photographer",
    "Book your florist",
    "Book hair and makeup",
    "Book other suppliers",
    "Find your dress",
    "Block book accommodation for your guests",
    "Book your wedding stationery",
    "Register a gift list",
    "Schedule brides, bridesmaids & groom’s wear fittings",
    "Meet with suppliers",
    "Finalise items such as chair covers, venue décor etc.",
    "Book your wedding transport",
    "Wedding cake tasting",
    "Research and book your honeymoon",
    "Start your beauty & wellness regime",
    "Starting planning hen and stag do’s",
    "Have your engagement shoot",
    "Organise your hair and makeup trial",
    "Have a menu tasting",
    "Book final dress fittings",
    "Buy your wedding rings",
    "Send out your wedding invitations",
    "Pick your first dance song",
    "Buy gifts for your bridal party",
    "Write wedding speeches and vows",
    "Chase up outstanding RSVPs",
    "Sort the seating plan",
    "Attend final fitting",
    "Finalise details with all your suppliers & create a contact list",
    "Arrange a wedding rehearsal",
    "Stag and Hen parties to take place",
    "Pack for your honeymoon if heading straight off",
    "Pack a bag of essentials eg. Blister plasters, cash, deodorant, hair pins, safety pins!",
    "Have final your beauty treatments",
    "Break in your wedding shoes"
];
